schema_version: 1

context:
  name: latform
  version: "0.1.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/latform-${{ version }}.tar.gz
  sha256: 492cd82f101e9f0882a3b2e1dadf4dc8cc624acfb6539d233fe2f962a64a7332

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  python:
    entry_points:
      - latform = latform.main:cli_main
      - latform-graph = latform.graph:cli_main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=60
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=${{ python_min }}
    - rich
    - typing_extensions

tests:
  - python:
      imports:
        - latform
      pip_check: true
  - requirements:
      run:
        - pip
    script:
      - latform --help
      - latform-graph --help

about:
  summary: Bmad lattice parser/formatter tool
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/ken-lauer/latform

extra:
  recipe-maintainers:
    - ken-lauer
